
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-secret
type: Opaque
data:
  CLICKHOUSE_PASSWORD: Y2xpY2tob3VzZQ==
  CLICKHOUSE_DATABASE: Y2xpY2tob3VzZQ==
  CLICKHOUSE_USER: Y2xpY2tob3VzZQ==

