apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
spec:
  selector:
    app: clickhouse  # Label for the ClickHouse pods (matches the Deployment's selector)
  ports:
    - protocol: TCP
      port: 7854  # Port you want to expose from the service
      targetPort: 8123  # Port your ClickHouse pods are listening on
      nodePort: 30794
  type: LoadBalancer
