apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-pv
spec:
  capacity:
    storage: 1Gi  # Specify the desired storage size
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  # Specify the storage class 
  hostPath:
    path: /PV  # Replace with the actual host path
